### ISSUE TITLE
get_client_random时报错：Error: access violation accessing 0x30

### ISSUE THREAD

**Issue by Ellery221Holmes** [mikusjelly/saam#5]
frida调用ssl.js时，执行到
`client_random += ("0" + Memory.readU8(p.add(i)).toString(16).toUpperCase()).substr(-2);`
时，报错
Error: access violation accessing 0x30.
看了下日志，发现s3_state_p=0x0。
求解？

【环境】
三星s6 edge Android 7.0.1
frida-server-12.2.29-android-arm64

【DEBUG日志】
SSL_read enter ssl=0xacbbf000 buf=0xacafe000 num=0x2000
get_address_port_pair sockfd=65 isRead=true
get_address_port_pair _addr=0 _port=443
get_address_port_pair _addr=0 _port=46899
get_master_key ssl=0xacbbf000
get_master_key session=0xacbbf280
get_master_key p=0xacbbf290
get_master_key masterkey=D9167BF3DAAD73B61B043C09C48F4AA013E499FE52919994CBE013B6A842B25EC56C8B90E3B0FDD0E358390D574A75D6
get_client_random ssl=0xacbbf000
**SDK=[24,25] s3_state_p=0x0
get_client_random p=0x30**
{'type': 'error', 'description': 'Error: access violation accessing 0x30', 'stack': 'Error: access violation accessing 0x30\n    at get_client_random (/ssl.js:310)\n    at /ssl.js:332', 'fileName': '/ssl.js', 'lineNumber': 310, 'columnNumber': 1}
 SSL_read ret retval=0x13b

**Comment by kin9-0rz** [comment]
我的系统是LineageOS, Android 8.1.0，没有以上问题。

三星的手机有可能修改了SSL的一些代码，你可以自行适配 [get_client_random](https://github.com/mikusjelly/saam/blob/master/fscripts/mon/Network/ssl.js#L279)：
```
if (SDK >= 26) { // for android 8.0(26)/8.1(27)/9.0(28)
   // 我的手机执行的是这一段：
    // size_t SSL_get_client_random(const SSL *ssl, unsigned char *out, size_t outlen);
    if (!isUndefined(SSL_get_client_random)) {
      p = Memory.alloc(SSL3_RANDOM_SIZE); // bug? cannot free
      SSL_get_client_random(ssl, p, SSL3_RANDOM_SIZE);
    }
  } else if (SDK < 26 && SDK > 23) { // for android 7.1(25)/7.0(24)
    var s3_state_p = ptr(Memory.readU32(ssl.add(56))); // 56=0x38
    logd("SDK=[24,25] s3_state_p=" + s3_state_p);  // s3_state_p=0x0，如果为0肯定有问题
    p = s3_state_p.add(48); // 48 = 0x30
  } else if (SDK == 23) { // for android 6.0(23)
    var s3_state_p = ptr(Memory.readU32(ssl.add(84))); // 84=0x54
    logd("SDK=23 s3_state_p=" + s3_state_p);
    p = s3_state_p.add(188); // 192 = 0xC0
  } else if (SDK < 23) { // for android 5.1(22)/5.0(21)/4.4W(20)/4.4(19) ...
    var s3_state_p = ptr(Memory.readU32(ssl.add(88))); // 88=0x58
    logd("SDK<23 s3_state_p=" + s3_state_p);
    p = s3_state_p.add(192); // 192 = 0xC0
  } else {
    logi("[X] get_client_random: unexpected result!!!!!!!!!!!!!!!!!");
  }
```
此外，还有 [get_master_key](https://github.com/mikusjelly/saam/blob/master/fscripts/mon/Network/ssl.js#L237) 的代码，可能也需要适配。

---

如果你不需要分析pcap文件，可以直接：
```
var client_random = null;
```
不影响打印。

**Comment by Ellery221Holmes** [comment]
好的，多谢！换了台小米手机确实可以。

**Comment by kin9-0rz** [comment]
OK, 那我关闭这个issue了。
